[www]
user = www-data
group = www-data

; 9000番ポートでリッスン（NGINXから接続される）
listen = 0.0.0.0:9000

; プロセス管理
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

; セキュリティ設定
clear_env = no

; ログ設定
catch_workers_output = yes
php_admin_value[error_log] = /var/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on